### ISSUE TITLE
Channels aren't being reordered correctly

### ISSUE THREAD

**Issue by deansheather** [DiscordFM/shortwave-radio#4]
When the bot finishes streaming, it fails to reorder the channels correctly. This means that a staff member needs to reorder channels manually after transmission.

The code that *should* be handling reordering can be found at https://github.com/DiscordFM/shortwave-radio/blob/master/src/lib/numbers.js#L40 and https://github.com/DiscordFM/shortwave-radio/blob/master/src/lib/numbers.js#L130-L152.

I suspect the problem is that the code does not wait for the voice channel to be deleted, we should wait for the promise to finish (resolved or rejected) before we send the batch channel update request.

**Comment by Ovyerus** [comment]
Closed by #6
