### ISSUE TITLE
Voice client does not disconnect after transmission

### ISSUE THREAD

**Issue by deansheather** [DiscordFM/shortwave-radio#5]
The voice client doesn't disconnect after transmission, and there does not appear to be any code to handle this. This results in the bot staying floated on the sidebar of the guild until the whole shortwave-radio client is restarted.

The client disconnect code should be placed somewhere after the batch channel update request most likely, which can be found at https://github.com/DiscordFM/shortwave-radio/blob/master/src/lib/numbers.js#L151.

**Comment by Ovyerus** [comment]
Closed by #6
